### PR TITLE
Don't link the plugin against libvapoursynth

### PR DESCRIPTION
**Pull request by darealshinji**

### CODE REVIEW

**Comment by dwbuiten** [comment]
Have you tested this to work?

Will merge if so.

**Comment by darealshinji** [comment]
I didn't check it yet, but on my system gcc always links with -Wl,--as-needed and the plugin never declares a dependency on libvapoursynth.so. And running `readelf -s libd2vsource.so` doesn't reveal any VapourSynth symbols except VapourSynthPluginInit which is from the plugin itself.

**Comment by dwbuiten** [comment]
Right. I remember why this is here now. We need pkg-config to get us the location of the vapoursynth headers.

Removing this should be OK, if you also modify configure to make sure it for vapoursynth's --cflags too. Right now it just calls pkg-config on $DEPLIBS.

**Comment by darealshinji** [comment]
Now it does a separate check for VapourSynth.h. By the way the plugin isn't linked against libavutil as it should.

**Comment by dwbuiten** [comment]
> By the way the plugin isn't linked against libavutil as it should.

I will add when I merge.

**Comment by dwbuiten** [comment]
Merged.

**Pull request closed without merging**
