### PR TITLE
Fix ApplyRFF

### PR DESCRIPTION
**Pull request by dubhater**
Sorry about the broken code I sent last time!

### CODE REVIEW

**Comment by dwbuiten** [comment]
Is there an explanation of the rff change itself?

**Comment by dubhater** [comment]
The change? What do you mean?

**Comment by dwbuiten** [comment]
"Make it actually work" doesn't really tell me what the old code did or why it changed.

**Comment by dubhater** [comment]
On 12/23/2016 11:19 PM, Derek Buitenhuis wrote:
> "Make it actually work" doesn't really tell me what the old code did or why it changed.
>
Oh, there is a second paragraph in that commit message.

The old code was supposed to the same thing as the new code, but it was 
broken. The samples I tried recently were returned completely untouched 
(same number of frames, same frames). It's possible I, uh, never tested 
that old code before. Can't remember, but it's likely.

The old code was supposed to fix the problem that ApplyRFF did not 
handle bottom field first streams.

**Pull request merged**
